[package]
name = "kheish-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
parking_lot = { workspace = true }
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dependencies.kheish-codec]
path = "../kheish-codec"

[dependencies.kheish-types]
path = "../kheish-types"
