//! Daemon-owned audio generation backed by provider-specific runtimes.

use std::collections::BTreeMap;
use std::sync::Arc;

use anyhow::{Result, anyhow, bail};
use async_trait::async_trait;
use kheish_runtime::{
    OpenAiProviderConfig, OpenAiSpeechRequest, OpenAiSpeechSynthesizer, OpenRouterProviderConfig,
    OpenRouterSpeechRequest, OpenRouterSpeechSynthesizer, RuntimeObserver,
    resolve_openai_tts_model, resolve_openrouter_tts_model,
};
use sha2::{Digest, Sha256};

use crate::assets::{
    AssetProvenanceRecord, FileAssetStore, MAX_ASSET_BYTES, validate_supported_audio_payload,
};
use crate::control_tools::{
    GenerateAudioToolRequest, GenerateAudioToolResponse, ImageToolRouteOverride,
};
use crate::model_routing::ModelRouteConfig;

const MAX_AUDIO_INPUT_CHARS: usize = 4_096;
const MAX_AUDIO_INSTRUCTIONS_CHARS: usize = 4_000;
const MAX_AUDIO_VOICE_CHARS: usize = 96;
const MAX_AUDIO_FORMAT_CHARS: usize = 16;
const MAX_GENERATED_AUDIO_ASSETS: usize = 1;

/// One provider-specific generated audio payload.
#[derive(Clone, Debug, PartialEq, Eq)]
pub(crate) struct GeneratedAudioPayload {
    /// The normalized MIME type returned by the provider.
    pub media_type: String,
    /// The encoded audio bytes persisted by the daemon asset store.
    pub bytes: Vec<u8>,
}

/// One provider-specific audio-generation result batch.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub(crate) struct GeneratedAudioBatch {
    /// The provider that generated the audio.
    pub provider: String,
    /// The concrete provider model that generated the audio.
    pub model: String,
    /// The generated audio payloads.
    pub assets: Vec<GeneratedAudioPayload>,
    /// Optional transcript associated with the generated audio.
    pub transcript: Option<String>,
}

/// Run/session context used to stamp daemon-generated audio assets with provenance.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub(crate) struct AudioToolExecutionContext {
    /// The session that requested the audio operation.
    pub session_id: Option<String>,
    /// The run that requested the audio operation.
    pub run_id: Option<String>,
    /// The tool-call id that requested the audio operation.
    pub tool_call_id: Option<String>,
}

/// Provider-neutral audio-generation backend contract.
#[async_trait]
pub(crate) trait AudioGenerationBackend: Send + Sync {
    /// Returns the stable provider name exposed by this backend.
    fn provider(&self) -> &str;

    /// Generates one or more audio assets for the provided request.
    async fn generate(
        &self,
        request: &GenerateAudioToolRequest,
        model_override: Option<&str>,
    ) -> Result<GeneratedAudioBatch>;
}

/// One daemon-owned audio-generation service that persists generated bytes as assets.
pub(crate) struct AudioGenerationService {
    assets: Arc<FileAssetStore>,
    backends: BTreeMap<String, Arc<dyn AudioGenerationBackend>>,
    default_route_id: String,
}

/// OpenRouter-backed audio-generation backend.
pub(crate) struct OpenRouterAudioGenerationBackend {
    config: OpenRouterProviderConfig,
    observer: Arc<dyn RuntimeObserver>,
}

/// OpenAI-backed audio-generation backend.
pub(crate) struct OpenAiAudioGenerationBackend {
    config: OpenAiProviderConfig,
    observer: Arc<dyn RuntimeObserver>,
}

impl OpenAiAudioGenerationBackend {
    /// Builds one OpenAI-backed audio backend.
    pub(crate) fn from_config(
        mut config: OpenAiProviderConfig,
        observer: Arc<dyn RuntimeObserver>,
    ) -> Self {
        // Audio generation should not inherit an arbitrary text model from the route.
        config.model = resolve_openai_tts_model(&config.model);
        Self { config, observer }
    }
}

#[async_trait]
impl AudioGenerationBackend for OpenAiAudioGenerationBackend {
    fn provider(&self) -> &str {
        "openai"
    }

    async fn generate(
        &self,
        request: &GenerateAudioToolRequest,
        model_override: Option<&str>,
    ) -> Result<GeneratedAudioBatch> {
        let mut config = self.config.clone();
        if let Some(model) = model_override {
            config.model = resolve_openai_tts_model(model);
        }
        let response_format = request
            .format
            .as_deref()
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .map(ToString::to_string)
            .or_else(|| Some("mp3".to_string()));
        let generated = OpenAiSpeechSynthesizer::new(config, self.observer.clone())?
            .synthesize(&OpenAiSpeechRequest {
                input: request.input.clone(),
                instructions: request.instructions.clone(),
                voice: request.voice.clone(),
                response_format,
                speed: request.speed,
            })
            .await
            .map_err(|error| anyhow!(error.message))?;
        Ok(GeneratedAudioBatch {
            provider: self.provider().to_string(),
            model: generated.model,
            assets: vec![GeneratedAudioPayload {
                media_type: generated.media_type,
                bytes: generated.bytes,
            }],
            transcript: generated.transcript,
        })
    }
}

impl OpenRouterAudioGenerationBackend {
    /// Builds one OpenRouter-backed audio backend.
    pub(crate) fn from_config(
        mut config: OpenRouterProviderConfig,
        observer: Arc<dyn RuntimeObserver>,
    ) -> Self {
        let route_model = config.model.clone();
        config.model = if openrouter_route_model_supports_tts(&config, &route_model) {
            resolve_openrouter_tts_model(&route_model)
        } else {
            resolve_openrouter_tts_model("")
        };
        Self { config, observer }
    }
}

fn openrouter_route_model_supports_tts(config: &OpenRouterProviderConfig, model: &str) -> bool {
    if config
        .capability_for_model(model)
        .is_some_and(|capabilities| capabilities.audio_generation())
    {
        return true;
    }
    let model = model.trim().to_ascii_lowercase();
    model.contains("tts") || model.contains("speech")
}

#[async_trait]
impl AudioGenerationBackend for OpenRouterAudioGenerationBackend {
    fn provider(&self) -> &str {
        "openrouter"
    }

    async fn generate(
        &self,
        request: &GenerateAudioToolRequest,
        model_override: Option<&str>,
    ) -> Result<GeneratedAudioBatch> {
        let mut config = self.config.clone();
        if let Some(model) = model_override {
            config.model = resolve_openrouter_tts_model(model);
        }
        let response_format = request
            .format
            .as_deref()
            .map(str::trim)
            .filter(|value| !value.is_empty())
            .map(ToString::to_string)
            .or_else(|| Some("mp3".to_string()));
        let generated = OpenRouterSpeechSynthesizer::with_observer(config, self.observer.clone())?
            .synthesize(&OpenRouterSpeechRequest {
                input: request.input.clone(),
                instructions: request.instructions.clone(),
                voice: request.voice.clone(),
                response_format,
                speed: request.speed,
            })
            .await
            .map_err(|error| anyhow!(error.message))?;
        Ok(GeneratedAudioBatch {
            provider: self.provider().to_string(),
            model: generated.model,
            assets: vec![GeneratedAudioPayload {
                media_type: generated.media_type,
                bytes: generated.bytes,
            }],
            transcript: generated.transcript,
        })
    }
}

impl AudioGenerationService {
    /// Builds one audio-generation service from provider-neutral backends.
    pub(crate) fn new(
        backends: BTreeMap<String, Arc<dyn AudioGenerationBackend>>,
        default_route_id: String,
        assets: Arc<FileAssetStore>,
    ) -> Result<Self> {
        if !backends.contains_key(&default_route_id) {
            bail!(
                "audio-generation default route '{}' is not configured",
                default_route_id
            );
        }
        Ok(Self {
            assets,
            backends,
            default_route_id,
        })
    }

    /// Generates one or more daemon-owned audio assets.
    #[cfg(test)]
    pub(crate) async fn generate(
        &self,
        request: GenerateAudioToolRequest,
        preferred_route_id: Option<&str>,
        credential_scope: Option<&kheish_types::CredentialScope>,
    ) -> Result<GenerateAudioToolResponse> {
        self.generate_with_context(
            request,
            preferred_route_id,
            credential_scope,
            AudioToolExecutionContext::default(),
        )
        .await
    }

    /// Generates one or more daemon-owned audio assets with durable provenance context.
    pub(crate) async fn generate_with_context(
        &self,
        request: GenerateAudioToolRequest,
        preferred_route_id: Option<&str>,
        credential_scope: Option<&kheish_types::CredentialScope>,
        context: AudioToolExecutionContext,
    ) -> Result<GenerateAudioToolResponse> {
        validate_audio_generation_request(&request)?;
        let selected_route_id = select_audio_generation_route_id(
            &self.backends,
            &request.route,
            preferred_route_id,
            &self.default_route_id,
            credential_scope,
        )?;
        let backend = self.backends.get(selected_route_id).ok_or_else(|| {
            anyhow!("no audio-generation backend is configured for route {selected_route_id}")
        })?;
        let generated = backend
            .generate(&request, request.route.model.as_deref())
            .await?;
        self.persist_generated_audio(generated, selected_route_id, context, &request)
    }

    fn persist_generated_audio(
        &self,
        generated: GeneratedAudioBatch,
        route_id: &str,
        context: AudioToolExecutionContext,
        request: &GenerateAudioToolRequest,
    ) -> Result<GenerateAudioToolResponse> {
        validate_generated_audio_batch(&generated)?;
        let mut attachments = Vec::with_capacity(generated.assets.len());
        let output_count = generated.assets.len() as u32;
        let prompt_sha256 = audio_generation_prompt_sha256(request);
        for (index, asset) in generated.assets.iter().enumerate() {
            let media_type = normalize_generated_audio_media_type(&asset.media_type);
            let extension = preferred_extension_for_audio_media_type(&media_type)?;
            let mut record = self.assets.import_bytes_with_provenance(
                &format!(
                    "generated-audio-{}-{}.{}",
                    generated.model,
                    index + 1,
                    extension
                ),
                Some(&media_type),
                &asset.bytes,
                Some(AssetProvenanceRecord {
                    kind: "audio_generation".to_string(),
                    tool_name: "generate_audio".to_string(),
                    session_id: context.session_id.clone(),
                    run_id: context.run_id.clone(),
                    tool_call_id: context.tool_call_id.clone(),
                    route_id: Some(route_id.to_string()),
                    provider: generated.provider.clone(),
                    model: generated.model.clone(),
                    prompt_sha256: prompt_sha256.clone(),
                    source_assets: Vec::new(),
                    output_index: index as u32 + 1,
                    output_count,
                }),
            )?;
            if let Some(transcript) = generated.transcript.as_deref().map(str::trim)
                && !transcript.is_empty()
            {
                let text_asset = self.assets.import_bytes(
                    &format!("generated-audio-{}-{}.txt", generated.model, index + 1),
                    Some("text/plain"),
                    transcript.as_bytes(),
                )?;
                record = self.assets.attach_text_asset(&record.id, &text_asset)?;
            }
            attachments.push(record.attachment_ref());
        }
        Ok(GenerateAudioToolResponse {
            provider: generated.provider,
            model: generated.model,
            route_id: Some(route_id.to_string()),
            assets: attachments,
            transcript: generated.transcript,
        })
    }
}

pub(crate) fn audio_generation_backend_from_route(
    route_id: &str,
    route: &ModelRouteConfig,
    observer: Arc<dyn RuntimeObserver>,
) -> Result<Option<(String, Arc<dyn AudioGenerationBackend>)>> {
    match route {
        ModelRouteConfig::OpenAi(config) => Ok(Some((
            route_id.to_string(),
            Arc::new(OpenAiAudioGenerationBackend::from_config(
                config.clone(),
                observer,
            )),
        ))),
        ModelRouteConfig::OpenRouter(config) => Ok(Some((
            route_id.to_string(),
            Arc::new(OpenRouterAudioGenerationBackend::from_config(
                config.clone(),
                observer,
            )),
        ))),
        ModelRouteConfig::Anthropic(_) | ModelRouteConfig::Google(_) | ModelRouteConfig::XAi(_) => {
            Ok(None)
        }
    }
}

fn select_audio_generation_route_id<'a>(
    backends: &'a BTreeMap<String, Arc<dyn AudioGenerationBackend>>,
    route_override: &'a ImageToolRouteOverride,
    preferred_route_id: Option<&'a str>,
    default_route_id: &'a str,
    credential_scope: Option<&kheish_types::CredentialScope>,
) -> Result<&'a str> {
    if let Some(route_id) = route_override.provider.as_deref() {
        ensure_route_allowed(credential_scope, route_id)?;
        if backends.contains_key(route_id) {
            return Ok(route_id);
        }
        bail!("no audio-generation backend is configured for route {route_id}");
    }
    if let Some(route_id) = preferred_route_id
        .filter(|route_id| backends.contains_key(*route_id))
        .filter(|route_id| route_is_allowed(credential_scope, route_id))
    {
        return Ok(route_id);
    }
    if route_is_allowed(credential_scope, default_route_id) {
        return Ok(default_route_id);
    }
    if let Some(route_id) = backends
        .keys()
        .find(|route_id| route_is_allowed(credential_scope, route_id))
    {
        return Ok(route_id.as_str());
    }
    if credential_scope.is_some() {
        bail!("credential scope blocks all audio-generation routes");
    }
    Ok(default_route_id)
}

fn route_is_allowed(
    credential_scope: Option<&kheish_types::CredentialScope>,
    route_id: &str,
) -> bool {
    credential_scope.is_none_or(|scope| scope.is_empty() || scope.allows_route(route_id))
}

fn ensure_route_allowed(
    credential_scope: Option<&kheish_types::CredentialScope>,
    route_id: &str,
) -> Result<()> {
    anyhow::ensure!(
        route_is_allowed(credential_scope, route_id),
        "credential scope blocks route {route_id}"
    );
    Ok(())
}

fn validate_audio_generation_request(request: &GenerateAudioToolRequest) -> Result<()> {
    let input_chars = request.input.trim().chars().count();
    if input_chars == 0 {
        bail!("audio generation input must not be empty");
    }
    if input_chars > MAX_AUDIO_INPUT_CHARS {
        bail!(
            "audio generation input exceeds the {} character limit",
            MAX_AUDIO_INPUT_CHARS
        );
    }
    if let Some(instructions) = request.instructions.as_deref() {
        let instructions_chars = instructions.trim().chars().count();
        if instructions_chars > MAX_AUDIO_INSTRUCTIONS_CHARS {
            bail!(
                "audio generation instructions exceed the {} character limit",
                MAX_AUDIO_INSTRUCTIONS_CHARS
            );
        }
    }
    if let Some(voice) = request.voice.as_deref() {
        let voice = voice.trim();
        if voice.chars().count() > MAX_AUDIO_VOICE_CHARS {
            bail!(
                "audio generation voice exceeds the {} character limit",
                MAX_AUDIO_VOICE_CHARS
            );
        }
        if !voice.is_empty()
            && !voice.chars().all(|character| {
                character.is_ascii_alphanumeric() || matches!(character, '_' | '-')
            })
        {
            bail!("audio generation voice must contain only ASCII letters, digits, '_' or '-'");
        }
    }
    if let Some(format) = request.format.as_deref() {
        let format = format.trim().to_ascii_lowercase();
        if format.chars().count() > MAX_AUDIO_FORMAT_CHARS {
            bail!(
                "audio generation format exceeds the {} character limit",
                MAX_AUDIO_FORMAT_CHARS
            );
        }
        if !format.is_empty() && !audio_generation_format_supported(&format) {
            bail!("unsupported audio generation format `{format}`");
        }
    }
    if let Some(speed) = request.speed
        && (!speed.is_finite() || !(0.25..=4.0).contains(&speed))
    {
        bail!("audio generation speed must be between 0.25 and 4.0");
    }
    Ok(())
}

fn audio_generation_format_supported(format: &str) -> bool {
    matches!(
        format.trim().to_ascii_lowercase().as_str(),
        "mp3" | "wav" | "pcm" | "opus" | "aac" | "flac"
    )
}

fn validate_generated_audio_batch(generated: &GeneratedAudioBatch) -> Result<()> {
    if generated.assets.is_empty() {
        bail!("audio generation provider returned no assets");
    }
    if generated.assets.len() > MAX_GENERATED_AUDIO_ASSETS {
        bail!(
            "audio generation provider returned {} assets; at most {} is supported",
            generated.assets.len(),
            MAX_GENERATED_AUDIO_ASSETS
        );
    }
    for asset in &generated.assets {
        let media_type = normalize_generated_audio_media_type(&asset.media_type);
        preferred_extension_for_audio_media_type(&media_type)?;
        validate_generated_audio_payload(&media_type, &asset.bytes)?;
    }
    Ok(())
}

fn validate_generated_audio_payload(media_type: &str, bytes: &[u8]) -> Result<()> {
    if bytes.is_empty() {
        bail!("audio generation provider returned an empty payload");
    }
    if bytes.len() > MAX_ASSET_BYTES {
        bail!(
            "audio generation provider payload exceeds the {} byte limit",
            MAX_ASSET_BYTES
        );
    }
    match media_type {
        "audio/mp3" => validate_supported_audio_payload("audio/mpeg", bytes),
        "audio/x-wav" => validate_supported_audio_payload("audio/wav", bytes),
        "audio/x-aac" => validate_supported_audio_payload("audio/aac", bytes),
        "audio/x-flac" => validate_supported_audio_payload("audio/flac", bytes),
        "audio/x-m4a" => validate_supported_audio_payload("audio/m4a", bytes),
        "audio/mpeg" | "audio/mpga" | "audio/wav" | "audio/opus" | "audio/aac" | "audio/flac"
        | "audio/mp4" | "audio/m4a" | "audio/pcm" | "audio/l16" | "audio/l24" => {
            validate_supported_audio_payload(media_type, bytes)
        }
        other => bail!("unsupported generated audio media type {other}"),
    }
}

fn preferred_extension_for_audio_media_type(media_type: &str) -> Result<&'static str> {
    match media_type {
        "audio/mpeg" | "audio/mp3" => Ok("mp3"),
        "audio/wav" | "audio/x-wav" => Ok("wav"),
        "audio/pcm" | "audio/l16" | "audio/l24" => Ok("pcm"),
        "audio/opus" => Ok("opus"),
        "audio/aac" | "audio/x-aac" => Ok("aac"),
        "audio/flac" | "audio/x-flac" => Ok("flac"),
        "audio/mp4" => Ok("mp4"),
        "audio/m4a" | "audio/x-m4a" => Ok("m4a"),
        other => bail!("unsupported generated audio media type {other}"),
    }
}

fn normalize_generated_audio_media_type(media_type: &str) -> String {
    media_type
        .split(';')
        .next()
        .unwrap_or(media_type)
        .trim()
        .to_ascii_lowercase()
}

fn audio_generation_prompt_sha256(request: &GenerateAudioToolRequest) -> String {
    let mut hasher = Sha256::new();
    hash_labeled_text(&mut hasher, "input", request.input.trim());
    hash_labeled_text(
        &mut hasher,
        "instructions",
        request.instructions.as_deref().unwrap_or("").trim(),
    );
    hex::encode(hasher.finalize())
}

fn hash_labeled_text(hasher: &mut Sha256, label: &str, value: &str) {
    hasher.update(label.as_bytes());
    hasher.update([0]);
    hasher.update(value.len().to_be_bytes());
    hasher.update(value.as_bytes());
    hasher.update([0xff]);
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;
    use std::sync::Arc;

    use anyhow::Result;
    use async_trait::async_trait;
    use kheish_runtime::{
        NoopObserver, OpenAiProviderConfig, OpenRouterModelCapabilities, OpenRouterProviderConfig,
    };
    use kheish_types::CredentialScope;
    use tempfile::tempdir;

    use super::{
        AudioGenerationBackend, AudioGenerationService, AudioToolExecutionContext,
        GeneratedAudioBatch, GeneratedAudioPayload, audio_generation_backend_from_route,
    };
    use crate::assets::FileAssetStore;
    use crate::control_tools::{GenerateAudioToolRequest, ImageToolRouteOverride};
    use crate::model_routing::ModelRouteConfig;

    struct FakeAudioBackend {
        provider: &'static str,
        model: &'static str,
    }

    #[async_trait]
    impl AudioGenerationBackend for FakeAudioBackend {
        fn provider(&self) -> &str {
            self.provider
        }

        async fn generate(
            &self,
            _request: &GenerateAudioToolRequest,
            _model_override: Option<&str>,
        ) -> Result<GeneratedAudioBatch> {
            Ok(GeneratedAudioBatch {
                provider: self.provider.to_string(),
                model: self.model.to_string(),
                assets: vec![GeneratedAudioPayload {
                    media_type: "audio/mpeg".to_string(),
                    bytes: valid_mp3_payload(),
                }],
                transcript: Some("hello".to_string()),
            })
        }
    }

    struct FixedAudioBackend {
        media_type: &'static str,
        bytes: Vec<u8>,
    }

    #[async_trait]
    impl AudioGenerationBackend for FixedAudioBackend {
        fn provider(&self) -> &str {
            "openai"
        }

        async fn generate(
            &self,
            _request: &GenerateAudioToolRequest,
            _model_override: Option<&str>,
        ) -> Result<GeneratedAudioBatch> {
            Ok(GeneratedAudioBatch {
                provider: "openai".to_string(),
                model: "tts-model".to_string(),
                assets: vec![GeneratedAudioPayload {
                    media_type: self.media_type.to_string(),
                    bytes: self.bytes.clone(),
                }],
                transcript: None,
            })
        }
    }

    fn valid_mp3_payload() -> Vec<u8> {
        let mut bytes = vec![0xff, 0xfb, 0x90, 0x64];
        bytes.resize(417, 0);
        bytes
    }

    fn invalid_wav_payload() -> Vec<u8> {
        let data = [0i16, 1024, -1024, 2048]
            .iter()
            .flat_map(|sample| sample.to_le_bytes())
            .collect::<Vec<_>>();
        let fmt_chunk_size = 16u32;
        let data_chunk_size = data.len() as u32;
        let riff_size = 4 + (8 + fmt_chunk_size) + (8 + data_chunk_size);
        let mut bytes = Vec::new();
        bytes.extend_from_slice(b"RIFF");
        bytes.extend_from_slice(&riff_size.to_le_bytes());
        bytes.extend_from_slice(b"WAVE");
        bytes.extend_from_slice(b"fmt ");
        bytes.extend_from_slice(&fmt_chunk_size.to_le_bytes());
        bytes.extend_from_slice(&1u16.to_le_bytes());
        bytes.extend_from_slice(&1u16.to_le_bytes());
        bytes.extend_from_slice(&16_000u32.to_le_bytes());
        bytes.extend_from_slice(&(16_000u32 * 2).to_le_bytes());
        bytes.extend_from_slice(&4u16.to_le_bytes());
        bytes.extend_from_slice(&16u16.to_le_bytes());
        bytes.extend_from_slice(b"data");
        bytes.extend_from_slice(&data_chunk_size.to_le_bytes());
        bytes.extend_from_slice(&data);
        bytes
    }

    #[test]
    fn audio_generation_backend_from_route_supports_openai() -> Result<()> {
        let route = ModelRouteConfig::OpenAi(OpenAiProviderConfig::new("gpt-5.4", "test-key"));
        let (_, backend) =
            audio_generation_backend_from_route("openai", &route, Arc::new(NoopObserver))?
                .expect("openai audio backend should be configured");
        assert_eq!(backend.provider(), "openai");
        Ok(())
    }

    #[test]
    fn openrouter_audio_backend_maps_chat_route_to_default_tts() {
        let config = OpenRouterProviderConfig::new("openrouter/owl-alpha", "test-key");
        let backend =
            super::OpenRouterAudioGenerationBackend::from_config(config, Arc::new(NoopObserver));

        assert_eq!(backend.config.model, "openai/gpt-4o-mini-tts-2025-12-15");
    }

    #[test]
    fn openrouter_audio_backend_preserves_explicit_tts_route_model() {
        let model = "google/gemini-3.1-flash-tts-preview";
        let mut capabilities = BTreeMap::new();
        capabilities.insert(
            model.to_string(),
            OpenRouterModelCapabilities {
                text_input: true,
                audio_output: true,
                ..OpenRouterModelCapabilities::default()
            },
        );
        let config =
            OpenRouterProviderConfig::new(model, "test-key").with_model_capabilities(capabilities);
        let backend =
            super::OpenRouterAudioGenerationBackend::from_config(config, Arc::new(NoopObserver));

        assert_eq!(backend.config.model, model);
    }

    #[tokio::test]
    async fn audio_generation_service_prefers_named_routes() -> Result<()> {
        let temp = tempdir()?;
        let assets = Arc::new(FileAssetStore::new(temp.path())?);
        let mut backends = BTreeMap::new();
        backends.insert(
            "openrouter".to_string(),
            Arc::new(FakeAudioBackend {
                provider: "openrouter",
                model: "tts-model",
            }) as Arc<dyn AudioGenerationBackend>,
        );
        let service = AudioGenerationService::new(backends, "openrouter".to_string(), assets)?;
        let response = service
            .generate(
                GenerateAudioToolRequest {
                    input: "hello".to_string(),
                    instructions: None,
                    voice: None,
                    format: None,
                    speed: None,
                    route: ImageToolRouteOverride {
                        provider: Some("openrouter".to_string()),
                        model: None,
                    },
                },
                None,
                None,
            )
            .await?;
        assert_eq!(response.provider, "openrouter");
        assert_eq!(response.model, "tts-model");
        assert_eq!(response.route_id.as_deref(), Some("openrouter"));
        assert_eq!(response.assets.len(), 1);
        assert_eq!(response.transcript.as_deref(), Some("hello"));
        Ok(())
    }

    #[tokio::test]
    async fn audio_generation_service_records_provenance_and_transcript_attachment() -> Result<()> {
        let temp = tempdir()?;
        let assets = Arc::new(FileAssetStore::new(temp.path())?);
        let assets_for_assert = assets.clone();
        let mut backends = BTreeMap::new();
        backends.insert(
            "openrouter".to_string(),
            Arc::new(FakeAudioBackend {
                provider: "openrouter",
                model: "tts-model",
            }) as Arc<dyn AudioGenerationBackend>,
        );
        let service = AudioGenerationService::new(backends, "openrouter".to_string(), assets)?;
        let request = GenerateAudioToolRequest {
            input: "hello".to_string(),
            instructions: Some("speak neutrally".to_string()),
            voice: Some("alloy".to_string()),
            format: Some("mp3".to_string()),
            speed: Some(1.0),
            route: ImageToolRouteOverride::default(),
        };
        let expected_prompt_sha256 = super::audio_generation_prompt_sha256(&request);

        let response = service
            .generate_with_context(
                request,
                Some("openrouter"),
                None,
                AudioToolExecutionContext {
                    session_id: Some("session-audio".to_string()),
                    run_id: Some("run-audio".to_string()),
                    tool_call_id: Some("call-audio".to_string()),
                },
            )
            .await?;

        assert_eq!(response.route_id.as_deref(), Some("openrouter"));
        assert_eq!(response.assets.len(), 1);
        assert!(
            response.assets[0].text_uri.is_some(),
            "returned attachment should include attached transcript metadata"
        );
        let record = assets_for_assert
            .get(&response.assets[0].id)
            .ok_or_else(|| anyhow::anyhow!("missing generated audio asset"))?;
        assert_eq!(record.text_uri, response.assets[0].text_uri);
        assert_eq!(record.provenance.len(), 1);
        let provenance = &record.provenance[0];
        assert_eq!(provenance.kind, "audio_generation");
        assert_eq!(provenance.tool_name, "generate_audio");
        assert_eq!(provenance.session_id.as_deref(), Some("session-audio"));
        assert_eq!(provenance.run_id.as_deref(), Some("run-audio"));
        assert_eq!(provenance.tool_call_id.as_deref(), Some("call-audio"));
        assert_eq!(provenance.route_id.as_deref(), Some("openrouter"));
        assert_eq!(provenance.provider, "openrouter");
        assert_eq!(provenance.model, "tts-model");
        assert_eq!(provenance.prompt_sha256, expected_prompt_sha256);
        assert!(provenance.source_assets.is_empty());
        assert_eq!(provenance.output_index, 1);
        assert_eq!(provenance.output_count, 1);
        Ok(())
    }

    #[tokio::test]
    async fn audio_generation_service_validates_request_before_dispatch() -> Result<()> {
        let temp = tempdir()?;
        let assets = Arc::new(FileAssetStore::new(temp.path())?);
        let mut backends = BTreeMap::new();
        backends.insert(
            "openai".to_string(),
            Arc::new(FakeAudioBackend {
                provider: "openai",
                model: "tts-model",
            }) as Arc<dyn AudioGenerationBackend>,
        );
        let service = AudioGenerationService::new(backends, "openai".to_string(), assets)?;

        let error = service
            .generate(
                GenerateAudioToolRequest {
                    input: " ".to_string(),
                    ..GenerateAudioToolRequest::default()
                },
                None,
                None,
            )
            .await
            .expect_err("empty input should fail before provider dispatch");
        assert!(
            error.to_string().contains("input must not be empty"),
            "unexpected error: {error}"
        );

        let error = service
            .generate(
                GenerateAudioToolRequest {
                    input: "hello".to_string(),
                    format: Some("exe".to_string()),
                    ..GenerateAudioToolRequest::default()
                },
                None,
                None,
            )
            .await
            .expect_err("bad format should fail before provider dispatch");
        assert!(
            error
                .to_string()
                .contains("unsupported audio generation format"),
            "unexpected error: {error}"
        );
        Ok(())
    }

    #[tokio::test]
    async fn audio_generation_service_rejects_invalid_provider_audio_without_asset() -> Result<()> {
        let temp = tempdir()?;
        let assets = Arc::new(FileAssetStore::new(temp.path())?);
        let mut backends = BTreeMap::new();
        backends.insert(
            "openai".to_string(),
            Arc::new(FixedAudioBackend {
                media_type: "audio/mpeg",
                bytes: b"not-an-mp3".to_vec(),
            }) as Arc<dyn AudioGenerationBackend>,
        );
        let service = AudioGenerationService::new(backends, "openai".to_string(), assets.clone())?;

        let error = service
            .generate(
                GenerateAudioToolRequest {
                    input: "hello".to_string(),
                    ..GenerateAudioToolRequest::default()
                },
                None,
                None,
            )
            .await
            .expect_err("invalid provider audio should fail");
        assert!(
            error.to_string().contains("valid MP3"),
            "unexpected error: {error}"
        );
        assert!(
            assets.list(None).is_empty(),
            "invalid provider audio should not persist an asset"
        );
        Ok(())
    }

    #[tokio::test]
    async fn audio_generation_service_rejects_header_only_provider_audio_without_asset()
    -> Result<()> {
        for (media_type, bytes, expected) in [
            (
                "audio/mpeg",
                vec![0xff, 0xfb, 0x90, 0x64],
                "MP3 audio frame is truncated",
            ),
            ("audio/flac", b"fLaC\x80\x00\x00\x00".to_vec(), "valid FLAC"),
            ("audio/wav", invalid_wav_payload(), "block_align"),
            (
                "audio/mp4",
                {
                    let mut bytes = Vec::new();
                    bytes.extend_from_slice(&12u32.to_be_bytes());
                    bytes.extend_from_slice(b"ftyp");
                    bytes.extend_from_slice(b"M4A ");
                    bytes
                },
                "media data",
            ),
        ] {
            let temp = tempdir()?;
            let assets = Arc::new(FileAssetStore::new(temp.path())?);
            let mut backends = BTreeMap::new();
            backends.insert(
                "openai".to_string(),
                Arc::new(FixedAudioBackend { media_type, bytes })
                    as Arc<dyn AudioGenerationBackend>,
            );
            let service =
                AudioGenerationService::new(backends, "openai".to_string(), assets.clone())?;

            let error = service
                .generate(
                    GenerateAudioToolRequest {
                        input: "hello".to_string(),
                        ..GenerateAudioToolRequest::default()
                    },
                    None,
                    None,
                )
                .await
                .expect_err("header-only provider audio should fail");
            assert!(
                error.to_string().contains(expected),
                "unexpected error for {media_type}: {error}"
            );
            assert!(
                assets.list(None).is_empty(),
                "invalid provider audio should not persist an asset"
            );
        }
        Ok(())
    }

    #[tokio::test]
    async fn audio_generation_service_rejects_oversized_provider_audio_without_asset() -> Result<()>
    {
        let temp = tempdir()?;
        let assets = Arc::new(FileAssetStore::new(temp.path())?);
        let mut backends = BTreeMap::new();
        let mut bytes = valid_mp3_payload();
        bytes.resize(crate::assets::MAX_ASSET_BYTES + 1, 0);
        backends.insert(
            "openai".to_string(),
            Arc::new(FixedAudioBackend {
                media_type: "audio/mpeg",
                bytes,
            }) as Arc<dyn AudioGenerationBackend>,
        );
        let service = AudioGenerationService::new(backends, "openai".to_string(), assets.clone())?;

        let error = service
            .generate(
                GenerateAudioToolRequest {
                    input: "hello".to_string(),
                    ..GenerateAudioToolRequest::default()
                },
                None,
                None,
            )
            .await
            .expect_err("oversized provider audio should fail");
        assert!(
            error.to_string().contains("byte limit"),
            "unexpected error: {error}"
        );
        assert!(
            assets.list(None).is_empty(),
            "oversized provider audio should not persist an asset"
        );
        Ok(())
    }

    #[tokio::test]
    async fn audio_generation_service_rejects_routes_blocked_by_credential_scope() -> Result<()> {
        let temp = tempdir()?;
        let assets = Arc::new(FileAssetStore::new(temp.path())?);
        let mut backends = BTreeMap::new();
        backends.insert(
            "openrouter".to_string(),
            Arc::new(FakeAudioBackend {
                provider: "openrouter",
                model: "tts-model",
            }) as Arc<dyn AudioGenerationBackend>,
        );
        let service = AudioGenerationService::new(backends, "openrouter".to_string(), assets)?;
        let scope = CredentialScope {
            route_deny: vec!["openrouter".to_string()],
            ..CredentialScope::default()
        };

        let error = service
            .generate(
                GenerateAudioToolRequest {
                    input: "hello".to_string(),
                    instructions: None,
                    voice: None,
                    format: None,
                    speed: None,
                    route: ImageToolRouteOverride::default(),
                },
                Some("openrouter"),
                Some(&scope),
            )
            .await
            .expect_err("blocked audio route should fail");

        assert!(
            error
                .to_string()
                .contains("credential scope blocks all audio-generation routes"),
            "unexpected error: {error}"
        );
        Ok(())
    }
}
